# Generated by ChatGPT for Sprint 1 DB models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("flag", models.CharField(blank=True, max_length=2)),
                ("symbol", models.CharField(blank=True, max_length=8)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="CurrencyPair",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_currency", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pairs_as_base", to="api.currency")),
                ("quote_currency", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pairs_as_quote", to="api.currency")),
            ],
            options={
                "ordering": ["base_currency__code", "quote_currency__code"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioHolding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="holdings", to="api.currency")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="portfolio_holdings", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["user_id", "currency__code"],
            },
        ),
        migrations.AddIndex(
            model_name="currency",
            index=models.Index(fields=["code"], name="api_currenc_code_6a13d9_idx"),
        ),
        migrations.AddIndex(
            model_name="currency",
            index=models.Index(fields=["is_enabled"], name="api_currenc_is_enab_2c1b6e_idx"),
        ),
        migrations.AddIndex(
            model_name="currencypair",
            index=models.Index(fields=["is_enabled"], name="api_currenc_is_enab_9209f9_idx"),
        ),
        migrations.AddIndex(
            model_name="currencypair",
            index=models.Index(fields=["base_currency", "quote_currency"], name="api_currenc_base_cu_3e1ab2_idx"),
        ),
        migrations.AddIndex(
            model_name="portfolioholding",
            index=models.Index(fields=["user", "currency"], name="api_portfol_user_id_6a33b6_idx"),
        ),
        migrations.AddConstraint(
            model_name="currencypair",
            constraint=models.UniqueConstraint(fields=("base_currency", "quote_currency"), name="uniq_currency_pair_base_quote"),
        ),
        migrations.AddConstraint(
            model_name="currencypair",
            constraint=models.CheckConstraint(check=models.Q(("base_currency", django.db.models.expressions.F("quote_currency")), _negated=True), name="chk_base_not_equal_quote"),
        ),
        migrations.AddConstraint(
            model_name="portfolioholding",
            constraint=models.UniqueConstraint(fields=("user", "currency"), name="uniq_holding_user_currency"),
        ),
        migrations.AddConstraint(
            model_name="portfolioholding",
            constraint=models.CheckConstraint(check=models.Q(("amount__gte", 0)), name="chk_holding_amount_nonnegative"),
        ),
    ]
