# Generated by Django 4.2.28 on 2026-03-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_trade_pricehistory_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="recorded_at",
            field=models.DateTimeField(),
        ),
    ]
